services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_lama_shop
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGODB_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis_lama_shop
    restart: always
    ports:
      - "${SPRING_REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${SPRING_REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: lama_shop_app
    restart: always
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGODB_INITDB_DATABASE}?authSource=admin
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    ports:
      - "${SPRING_PORT}:8080"
    volumes:
      - uploads_data:/app/uploads

volumes:
  mongo_data:
  redis_data:
  uploads_data: